std = "lua51"

max_line_length = false
unused_args = false
ignore = {
    "12.", -- _G/UI template field assignment patterns used in WoW addons
    "6..", -- style warnings (whitespace/formatting)
}

read_globals = {
    "BOOKTYPE_SPELL",
    "ColorPickerFrame",
    "CreateFrame",
    "GetNumSpellTabs",
    "GetSpellTabInfo",
    "GetSpellBookItemName",
    "GetSpellBookItemTexture",
    "GetSpellBookItemInfo",
    "GetSpellBookItemLink",
    "IsPassiveSpell",
    "IsUsableSpell",
    "IsSpellInRange",
    "UnitDebuff",
    "UnitHealth",
    "UnitHealthMax",
    "UnitMana",
    "UnitManaMax",
    "UnitPowerType",
    "UnitInRange",
    "UnitInParty",
    "UnitInRaid",
    "UnitThreatSituation",
    "UnitIsConnected",
    "UnitIsDeadOrGhost",
    "UnitIsAFK",
    "UnitClass",
    "UnitIsUnit",
    "GetNumRaidMembers",
    "GetRaidRosterInfo",
    "GetNumPartyMembers",
    "RAID_CLASS_COLORS",
    "LibStub",
    "GetTime",
    "UIParent",
    "GameTooltip",
    "FauxScrollFrame_Update",
    "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_OnVerticalScroll",
    "EasyMenu",
    "StaticPopup_Show",
    "ChatEdit_InsertLink",
    "IsShiftKeyDown",
    "GetSpellLink",
    "GetSpellInfo",
    "InCombatLockdown",
    "DEFAULT_CHAT_FRAME",
    "InterfaceOptions_AddCategory",
    "InterfaceOptionsFrame_OpenToCategory",
    "UnitName",
    "GetRealmName",
    "UnitAura",
    "UnitExists",
    "UnitGUID",
    "date",
    "wipe",
    "pairs",
    "ipairs",
    "table",
    "string",
    "math",
    "tonumber",
    "tostring",
    "type",
    "pcall",
    "next",
    "_G",
}

globals = {
    "Painboy",
    "StaticPopupDialogs",
    "SLASH_PAINBOY1",
    "SLASH_PAINBOY2",
    "SlashCmdList",
    "PainboyDB",
    "PainboyGlobal",
}
